version: "3.9"

services:
  proxy:
    build: .
    ports:
      - 8080:80
    depends_on:
      - websocket
    environment:
      - TARGET_URIS=websocket:8080

  websocket:
    image: jmalloc/echo-server
    ports:
      - 8081:8080
